from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class FilterCondition:
    column: str
    operator: str
    value: str


@dataclass
class AnalysisCommand:
    """
    Standard command generated by the AI model.
    This is the ONLY format the Analysis Engine understands.
    """

    operation: str

    group_by: Optional[str] = None

    metric: Optional[str] = None

    aggregation: Optional[str] = None

    filters: List[FilterCondition] = field(default_factory=list)

    sort: Optional[str] = None

    limit: Optional[int] = None

    chart: Optional[str] = None

    x_axis: Optional[str] = None

    y_axis: Optional[str] = None