from dataclasses import dataclass, field
from typing import List, Optional

from models.analysis_step import AnalysisStep


@dataclass
class Visualization:
    """
    Describes how the analysis result should be visualized.
    """

    chart_type: str

    x_axis: Optional[str] = None

    y_axis: Optional[str] = None

    title: Optional[str] = None


@dataclass
class ExecutionPlan:
    """
    Represents the complete execution plan generated by the AI Planner.
    """

    steps: List[AnalysisStep] = field(default_factory=list)

    visualization: Optional[Visualization] = None

    reasoning: Optional[str] = None